root: true
parserOptions:
  parser: babel-eslint
  sourceType: module
env:
  serviceworker: true 
  browser: true
extends:
  - plugin:vue/recommended
  - standard
plugins:
  - vue
globals:
  ga: true
  cordova: true
  __statics: true
rules:
  # allow async-await
  generator-star-spacing: off

  arrow-parens: 
    - error
    - as-needed
  import/first: 0
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/extensions: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  brace-style: 
    - 2
    - 1tbs
    - allowSingleLine: true
  space-before-function-paren:
    - error
    - never
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - double
  no-multiple-empty-lines: 
    - error
    - max: 1 
      maxBOF: 0
  no-var: error
  no-unused-vars: 0
  no-console: 0
  object-curly-spacing:
    - error
    - always
  no-multi-spaces: error
  no-self-assign: 0
  prefer-const: error
  prefer-template: error
  template-curly-spacing:
    - error
    - never
